package:
  name: roq-cpp-fix-client-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CFLAGS=-O3                                                                                                                                                
    - CPPFLAGS=-O3  # [linux]                                                                                                                                   
    - CPPFLAGS=-O3 -D_LIBCPP_DISABLE_AVAILABILITY  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - libabseil
    - roq-api
    - roq-codec
    - roq-fix
    - roq-flags
    - roq-io
    - roq-logging
    - roq-oss-benchmark
    - roq-oss-magic_enum
    - roq-oss-nameof
    - roq-oss-unordered_dense
    - roq-utils
    - roq-web

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ FIX Client (a template project)
