package:
  name: roq-cpp-fix-client-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clang-format
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - libabseil
    - magic_enum
    - roq-api
    - roq-fix
    - roq-flags
    - roq-io
    - roq-logging
    - roq-oss-benchmark
    - roq-oss-nameof
    - roq-oss-unordered_dense
    - roq-utils
    - roq-web

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C++ FIX Client (a template project)
