package:
  name: roq-fix-client
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - libabseil
    - roq-codec
    - roq-flags
    - roq-io
    - roq-oss-unordered_dense
    - roq-utils
    - roq-web

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FIX Client (a template project)
