package:
  name: roq-fix-strategy-template
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - roq-io
    - roq-codec
    - roq-flags
    - abseil-cpp
    - catch2

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FIX Strategy (a template project)
